# Generated by Django 6.0.4 on 2026-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='alumni_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
