# Generated by Django 6.0.4 on 2026-04-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='interaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
