# Generated by Django 6.0.4 on 2026-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_contact_interaction_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='meeting_context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
