# Generated by Django 6.0.4 on 2026-04-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_contact_meeting_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='meeting_context',
        ),
    ]
