# Generated by Django 6.0.4 on 2026-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_contact_meeting_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_dashboard_email_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
