# Generated by Django 6.0.4 on 2026-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_last_dashboard_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_attended',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
