# Generated by Django 6.0.4 on 2026-04-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_profession_user_school_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='meeting_context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
