# Generated by Django 6.0.4 on 2026-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_contact_meeting_context_contact_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='action_items',
            field=models.TextField(blank=True, help_text='Action items or follow-ups', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='discussion_summary',
            field=models.TextField(blank=True, help_text='Important points discussed during interaction', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('coffee_meeting', 'Coffee Meeting'), ('phone_call', 'Phone Call'), ('video_call', 'Video Call'), ('online_conference', 'Online Conference'), ('physical_meetup', 'Physical Meetup'), ('whatsapp_call', 'WhatsApp Call'), ('chatting', 'Chatting'), ('text_message', 'Text Message'), ('email', 'Email'), ('social_media', 'Social Media'), ('other', 'Other')], default='physical_meetup', max_length=30),
        ),
        migrations.AddField(
            model_name='interaction',
            name='location',
            field=models.CharField(blank=True, help_text='Location if applicable', max_length=255, null=True),
        ),
    ]
