# Generated by Django 6.0.4 on 2026-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_interaction_action_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_email_count_today',
            field=models.IntegerField(default=0),
        ),
    ]
